### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference during merge of copied and generated flows. 

### ISSUE THREAD

**Issue by dkolistratova** [intel-go/nff-go#294]
Program failed with error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x4e1155]

goroutine 21 [running, locked to thread]:
github.com/intel-go/nff-go/packet.(*Packet).GetRawPacketBytes(...)
       /projects/src/github.com/intel-go/nff-go/packet/packet.go:700
github.com/intel-go/nff-go/flow.pcopy(0x69a200, 0xc42000c120, 0xc4201a40c0, 0xc42018c000, 0x0, 0x0, 0x0)
       /projects/src/github.com/intel-go/nff-go/flow/flow.go:1139 +0x435
github.com/intel-go/nff-go/flow.(*scheduler).startFF.func1(0xc42018a140, 0x3)
        /projects/src/github.com/intel-go/nff-go/flow/scheduler.go:202 +0x238
created by github.com/intel-go/nff-go/flow.(*scheduler).startFF
        /projects/src/github.com/intel-go/nff-go/flow/scheduler.go:196 +0x22a

Code:

```go
package main

import (
	"log"
	"sync"
	"sync/atomic"
	"time"

	"github.com/intel-go/nff-go/flow"
	"github.com/intel-go/nff-go/packet"
	"github.com/intel-go/nff-go/test/stability/stabilityCommon"
)

var (
	totalPackets uint64 = 100

	payloadSize uint   = 16

	sentPacketsGroup1 uint64
	
	recvPackets       uint64
	testDoneEvent *sync.Cond
	progStart     time.Time

	// T second timeout is used to let generator reach required speed
	// During timeout packets are skipped and not counted
	T = 10 * time.Second
)

func main() {
	// Init NFF-GO system
	config := flow.Config{
		DPDKArgs: []string{"--log-level=0"},
	}
	flow.CheckFatal(flow.SystemInit(&config))
	var m sync.Mutex
	testDoneEvent = sync.NewCond(&m)

	flow1 := flow.SetGenerator(generatePacketGroup1, nil)

	flow2 := flow.SetGenerator(generatePacketGroup1, nil)


	flow.CheckFatal(flow.SetStopper(flow2))
	var err error
	flow2, err = flow.SetCopier(flow1)
	flow.CheckFatal(err)

	checkedFlow, err := flow.SetMerger(flow1, flow2)
	flow.CheckFatal(err)
	
	flow.CheckFatal(flow.SetHandler(checkedFlow, checkPackets, nil))
	flow.CheckFatal(flow.SetStopper(checkedFlow))
	
	// Start pipeline
	go func() {
		err = flow.SystemStart()
	}()
	flow.CheckFatal(err)
	progStart = time.Now()
	
	// Wait for enough packets to arrive
	testDoneEvent.L.Lock()
	testDoneEvent.Wait()
	testDoneEvent.L.Unlock()
}


func generatePacketGroup1(pkt *packet.Packet, context flow.UserContext) {
	if pkt == nil {
		log.Fatal("Failed to create new packet")
	}
	if packet.InitEmptyIPv4UDPPacket(pkt, payloadSize) == false {
		log.Fatal("Failed to init empty packet")
	}

	// We do not consider the start time of the system in this test
	if time.Since(progStart) >= T && atomic.LoadUint64(&recvPackets) < totalPackets {
		atomic.AddUint64(&sentPacketsGroup1, 1)
	}
}


// Count and check packets in received flow
func checkPackets(pkt *packet.Packet, context flow.UserContext) {
	if time.Since(progStart) < T || stabilityCommon.ShouldBeSkipped(pkt) {
		return
	}
	if atomic.AddUint64(&recvPackets, 1) >= totalPackets {
		testDoneEvent.Signal()
		return
	}
}
```
By the way, there is no such problem in the same code with fast generator!

First I tried the same code with many totalpackets, got really huge amount of the same warnings:
"WARNING: GeneratePacketFromByte: Cannot append mbuf", then run with 100 packets and got this error.

**Comment by dkolistratova** [comment]
There is no closing in example, it is generator + copy.

**Comment by dkolistratova** [comment]
made smaller:

```go
package main

import (
	"sync"
	"sync/atomic"
	"time"

	"github.com/intel-go/nff-go/flow"
	"github.com/intel-go/nff-go/packet"
)

var (
	totalPackets uint64 = 100
	payloadSize uint   = 16
	recvPackets       uint64
	progStart     time.Time
	m sync.Mutex
	testDoneEvent = sync.NewCond(&m)
	T = 10 * time.Second
)

func main() {
	config := flow.Config{
		DPDKArgs: []string{"--log-level=0"},
	}
	flow.CheckFatal(flow.SystemInit(&config))

	flow1 := flow.SetGenerator(generatePacketGroup1, nil)

	flow2, err := flow.SetCopier(flow1)
	flow.CheckFatal(err)
	
	flow.CheckFatal(flow.SetHandler(flow2, checkPackets, nil))

	flow.CheckFatal(flow.SetStopper(flow1))
	flow.CheckFatal(flow.SetStopper(flow2))
	
	go func() {
		err = flow.SystemStart()
	}()
	flow.CheckFatal(err)
	
	progStart = time.Now()

	testDoneEvent.L.Lock()
	testDoneEvent.Wait()
	testDoneEvent.L.Unlock()
}


func generatePacketGroup1(pkt *packet.Packet, context flow.UserContext) {
	if pkt == nil {
		panic("Failed to create new packet")
	}
	if packet.InitEmptyIPv4UDPPacket(pkt, payloadSize) == false {
		panic("Failed to init empty packet")
	}
}

func checkPackets(pkt *packet.Packet, context flow.UserContext) {
	if time.Since(progStart) < T{
		return
	}
	if atomic.AddUint64(&recvPackets, 1) >= totalPackets {
		testDoneEvent.Signal()
	}
}
```

**Comment by ifilippov** [comment]
Fix by https://github.com/intel-go/nff-go/commit/fbf5a71f7c6757a43cdb41f6f05c766a03e9ba2f. Closed this.
