### ISSUE TITLE
Test crashes in CI

### ISSUE THREAD

**Issue by gshimansky** [intel-go/nff-go#355]
I just noticed that on recent develop branch a "vector partition" test had crashed with SIGSEGV

```
[05:31:54]	[Step 5/5] 2018/05/16 07:31:54 1 panic: runtime error: invalid memory address or nil pointer dereference
[05:31:54]	[Step 5/5] 2018/05/16 07:31:54 1 [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x519fa8]
[05:31:54]	[Step 5/5] 2018/05/16 07:31:54 1 
[05:31:54]	[Step 5/5] 2018/05/16 07:31:54 1 goroutine 7 [running, locked to thread]:
[05:31:54]	[Step 5/5] 2018/05/16 07:31:54 1 main.addF2(0x7ff3f3b5eb40)
[05:31:54]	[Step 5/5] 2018/05/16 07:31:54 1 	/localdisk/tc_agent/work/src/github.com/intel-go/nff-go/test/stability/testSingleWorkingFF/testSingleWorkingFF.go:592 +0x38
[05:31:54]	[Step 5/5] 2018/05/16 07:31:54 1 main.vectorL3Handler(0xc421424000, 0x20, 0x20, 0xc421426008, 0x0, 0x0)
[05:31:54]	[Step 5/5] 2018/05/16 07:31:54 1 	/localdisk/tc_agent/work/src/github.com/intel-go/nff-go/test/stability/testSingleWorkingFF/testSingleWorkingFF.go:556 +0x5a
[05:31:54]	[Step 5/5] 2018/05/16 07:31:54 1 github.com/intel-go/nff-go/flow.vHandle(0xc421424000, 0x20, 0x20, 0xc421426008, 0xc421428020, 0xc4200ac070, 0x0, 0x0)
[05:31:54]	[Step 5/5] 2018/05/16 07:31:54 1 	/localdisk/tc_agent/work/src/github.com/intel-go/nff-go/flow/flow.go:1258 +0x66
[05:31:54]	[Step 5/5] 2018/05/16 07:31:54 1 github.com/intel-go/nff-go/flow.segmentProcess(0x6e7460, 0xc4200960e0, 0xc420076120, 0xc420076180, 0xc4213f4000, 0xc421406000, 0x4, 0x4)
[05:31:54]	[Step 5/5] 2018/05/16 07:31:54 1 	/localdisk/tc_agent/work/src/github.com/intel-go/nff-go/flow/flow.go:995 +0x8e1
[05:31:54]	[Step 5/5] 2018/05/16 07:31:54 1 github.com/intel-go/nff-go/flow.(*scheduler).startFF.func1(0xc4213f20a0, 0x2)
[05:31:54]	[Step 5/5] 2018/05/16 07:31:54 1 	/localdisk/tc_agent/work/src/github.com/intel-go/nff-go/flow/scheduler.go:217 +0x24c
[05:31:54]	[Step 5/5] 2018/05/16 07:31:54 1 created by github.com/intel-go/nff-go/flow.(*scheduler).startFF
[05:31:54]	[Step 5/5] 2018/05/16 07:31:54 1 	/localdisk/tc_agent/work/src/github.com/intel-go/nff-go/flow/scheduler.go:211 +0x253
```

**Comment by ifilippov** [comment]
These function is used in all tests. Some packet doesn't have place for additional data variable. Cannot reproduce at bare metal, is VM fail stable?

**Comment by gshimansky** [comment]
No, it is probably rare and I didn't see it again.

**Comment by gshimansky** [comment]
The same crash is reproducible all the time when VMs are connected via bridge instead of UDP tunnel. A lot of extra packets are traveling in the network in this connection mode.

**Comment by gshimansky** [comment]
Unknown packets apparently are STP packets generated by the bridge. These can be disabled with `brctl` command and `virsh net-edit`.
