### ISSUE TITLE
Crash in checksum tests when VMs are connected via bridge

### ISSUE THREAD

**Issue by gshimansky** [intel-go/nff-go#374]
If VM connection is changed to a bridge from UDP tunnel I see a lot of crashes like this:
```
2018/05/29 15:59:57 0 fatal error: unexpected signal during runtime execution
2018/05/29 15:59:57 0 [signal SIGSEGV: segmentation violation code=0x1 addr=0x100000012 pc=0x6aa7c8]
2018/05/29 15:59:57 0
2018/05/29 15:59:57 0 runtime stack:
2018/05/29 15:59:57 0 runtime.throw(0x7037c9, 0x2a)
2018/05/29 15:59:57 0   /opt/go/src/runtime/panic.go:605 +0x95
2018/05/29 15:59:57 0 runtime.sigpanic()
2018/05/29 15:59:57 0   /opt/go/src/runtime/signal_unix.go:351 +0x2b8
2018/05/29 15:59:57 0
2018/05/29 15:59:57 0 goroutine 5 [syscall, locked to thread]:
2018/05/29 15:59:57 0 runtime.cgocall(0x500e90, 0xc42003de18, 0x703461)
2018/05/29 15:59:57 0   /opt/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc42003ddd8 sp=0xc42003dd98 pc=0x430274
2018/05/29 15:59:57 0 github.com/intel-go/nff-go/low._Cfunc_port_init(0x10001, 0x7fe8e801da80, 0x101, 0x0)
2018/05/29 15:59:57 0   github.com/intel-go/nff-go/low/_obj/_cgo_gotypes.go:634 +0x4d fp=0xc42003de18 sp=0xc42003ddd8 pc=0x4df24d
2018/05/29 15:59:57 0 github.com/intel-go/nff-go/low.CreatePort.func1(0x10001, 0x7fe8e801da80, 0x7fe8e8010101, 0xc42003dea0)
2018/05/29 15:59:57 0   /localdisk/gashiman/go/src/github.com/intel-go/nff-go/low/low.go:516 +0x93 fp=0xc42003de50 sp=0xc42003de18 pc=0x4e1c83
2018/05/29 15:59:57 0 github.com/intel-go/nff-go/low.CreatePort(0x101000000010001, 0xc42003df68, 0x4)
2018/05/29 15:59:57 0   /localdisk/gashiman/go/src/github.com/intel-go/nff-go/low/low.go:516 +0x72 fp=0xc42003ded0 sp=0xc42003de50 pc=0x4e0df2
2018/05/29 15:59:57 0 github.com/intel-go/nff-go/flow.SystemStart(0x0, 0x0)
2018/05/29 15:59:57 0   /localdisk/gashiman/go/src/github.com/intel-go/nff-go/flow/flow.go:489 +0x368 fp=0xc42003dfb8 sp=0xc42003ded0 pc=0x4f2518
2018/05/29 15:59:57 0 main.executeTest.func1(0xc420040400)
2018/05/29 15:59:57 0   /localdisk/gashiman/go/src/github.com/intel-go/nff-go/test/stability/testCksum/testCksum.go:268 +0x22 fp=0xc42003dfd8 sp=0xc42003dfb8 pc=0x4fce22
2018/05/29 15:59:57 0 runtime.goexit()
2018/05/29 15:59:57 0   /opt/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42003dfe0 sp=0xc42003dfd8 pc=0x484471
2018/05/29 15:59:57 0 created by main.executeTest
2018/05/29 15:59:57 0   /localdisk/gashiman/go/src/github.com/intel-go/nff-go/test/stability/testCksum/testCksum.go:267 +0x538
2018/05/29 15:59:57 0
2018/05/29 15:59:57 0 goroutine 1 [semacquire]:
2018/05/29 15:59:57 0 sync.runtime_notifyListWait(0xc42005a590, 0xc400000000)
2018/05/29 15:59:57 0   /opt/go/src/runtime/sema.go:507 +0x110
2018/05/29 15:59:57 0 sync.(*Cond).Wait(0xc42005a580)
2018/05/29 15:59:57 0   /opt/go/src/sync/cond.go:56 +0x80
2018/05/29 15:59:57 0 main.executeTest(0x1, 0x10001, 0x0, 0x7052b4)
2018/05/29 15:59:57 0   /localdisk/gashiman/go/src/github.com/intel-go/nff-go/test/stability/testCksum/testCksum.go:276 +0x578
2018/05/29 15:59:57 0 main.main()
2018/05/29 15:59:57 0   /localdisk/gashiman/go/src/github.com/intel-go/nff-go/test/stability/testCksum/testCksum.go:114 +0x51d
```

**Comment by ifilippov** [comment]
It is about port... Something went wrong with this bug:-)

**Comment by gshimansky** [comment]
Crash command line is
```
./testCksum -testScenario=1 -hwol -ipv4 -tcp -number=50000 -inport=1 -outport=0 -speed=5000
```
After I tried assigning all to one port like
```
./testCksum -testScenario=1 -hwol -ipv4 -tcp -number=50000 -inport=0 -outport=0 -speed=5000 -dpdk --log-level=8
```
crash disappeared and didn't happen again even after VM reboot.

**Comment by gshimansky** [comment]
Closed because it is no longer reproducible. The reason is unknown.
